name: deploy in vercel
on:
  push:
    branches: [feat]
  pull_request:
    branches: [feat]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: install netlify    
      run: npm i -g vercel
    - name: deploy to netlify
      run: npx vercel --prod
